name: Terremoto
main: me.ninzinhu.terremoto.TerremotoPlugin
version: ${project.version}
api-version: 1.19
commands:
  terremoto:
    description: Inicia o evento de terremoto e reinicia o servidor após 5 minutos.
    usage: /terremoto
    permission: terremoto.use
permissions:
  terremoto.use:
    description: Permite usar o comando /terremoto
    default: op
